### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by Weifanwong** [GemsLab/REGAL#4]

**Comment by markheimann** [comment]
Hi Wei,

It’s certainly possible that a bug was introduced in the modifications.  I’d check everything thoroughly, but I should also mention that it’s also possible REGAL performs poorly on this dataset.  I wouldn’t be thrilled about that, but we know that our method makes some arguably strong assumptions about the data and thus has some limitations (as we state in the paper).  For example, we assume that ground truth alignment nodes often have similar degrees even in the two networks.  This is definitely not always the case in the real world (I know I have a very different number of Facebook friends and Twitter followers ;) ), but it is an assumption that can be made and has been made in prior literature (refer to our paper for citations).  Our experiment design, where we model different networks as noisy permutations, reflects this assumption (and follows the prior works that make a similar one.)  I don’t know anything about this Flickr and LastFM dataset, but it is possible that that the assumption about degree similarity between ground truth aligning nodes (or others that we hadn’t considered) is violated.  

If you were looking for possible ways to extend our methodology, my guess is a more clever alignment procedure than our simply greedy matching approach would be needed (many other optimization-based methods do this already, because they don’t have the benefit of embeddings.). Otherwise, if you already have your own methodology, perhaps we are an easy baseline to beat for this dataset (which would be good for you of course :) )   Again, this assumes the best case for your code (that it’s bug free), and it’s certainly worth double checking to make sure this is the case.  But I thought I’d mention it a) so that you don’t drive yourself crazy if your code is bug free and REGAL simply isn’t working well, and b) to give you an idea of the limitations and possible room for extension (if that’s a research direction you were interested in) of REGAL, as you’ll probably run up against them at some point.  


Best,
Mark
